sudo: false
language: node_js
node_js:
  - node
env:
  - ARANGODB_VERSION=devel ARANGO_VERSION=30200
before_install:
  - curl https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh | bash
script:
  - yarn run lint && yarn run dist && yarn run ci
after_script:
  - kill -9 $(pgrep arangod)
cache:
  yarn: true
  directories:
    - node_modules
